name: Weekly Update

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run sync-consensus-specs.sh
        run: |
          chmod +x ./scripts/sync-consensus-specs.sh
          ./scripts/sync-consensus-specs.sh
      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add docs/consensus/specs
            git commit -m "feat(specs): update consensus specs"
            git push
          else
            echo "No changes to commit."
          fi
